name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H 3.218.187.2 >> ~/.ssh/known_hosts
          echo "SSH setup was Succesfull"

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ubuntu@3.218.187.2 << 'EOF'
            cd /var/www/znz
            sudo chown -R ubuntu:ubuntu .
            sudo chmod -R 755 .
            test -d /todo-api && sudo rm -rf /todo-api
            git clone https://github.com/devops689/todo-api.git
            echo "cloned repo..."
            cd /todo-api
            git checkout main
            echo "checked out main branch..."
            npm install --production
            echo "installed npm packages..."
            pm2 restart SMAC || pm2 start ./src/index.js --name SMAC
            exit
          EOF
          echo "Deployment was Succesfull"
