name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup SSH Connection
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/id_rsa ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
            sudo chown -R ubuntu:ubuntu .
            sudo chmod -R 755 .
            cd /var/www/znz
            test -d /todo-api && sudo rm -rf ./*
            git clone ${{ secrets.REPO_LINK }}
            cd /var/www/znz/todo-api
            git checkout main
            npm install --production
            echo "NODE_ENV=production" > .env
            echo "SERVER_PORT=${{ secrets.SERVER_PORT }}" >> .env
            echo "DB_URL=${{ secrets.DB_URL }}" >> .env
            echo "DB_PORT=${{ secrets.DB_PORT }}" >> .env
            echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
            echo "DB_USER=${{ secrets.DB_USER }}" >> .env
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
            pm2 restart /var/www/znz/todo-api/src/index.js
            exit
          EOF
